spring:
  application:
    name: chat-app

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: mysql
    password: root


jwt:
  key: jwC6B92XzKTOoYjDQ6f3zV4UnOUOYF5fFw/NbeEJ5fs=
  expiration: 120000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  logging:
    level:
      org:
        springframework:
          web: DEBUG
        security: DEBUG