spring:
  application:
    name: chat-app

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    generate-ddl: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: mysql
    password: root


jwt:
  key: Z3NlQmQzR2hkUjJZcG5IU2hmbU9FRFpCRkpDdHZSY05DUzFEbjJTRWtaTnZoRkQ0M0tJV0JFUkZGcz0=
  expiration: 3600000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  logging:
    level:
      org:
        springframework:
          web: DEBUG
        security: DEBUG